### ISSUE TITLE
No such file or directory "key_technical_words.txt"

### ISSUE THREAD

**Issue by tyk15886924522** [LijunRio/Ultrasound-Report-Generation#1]
> Traceback (most recent call last):
>   File "KMVE_RG/my_main.py", line 13, in &lt;module&gt;
>     from modules.tokenizers import Tokenizer
>   File "/home/tyk/Ultrasound-Report-Generation/KMVE_RG/modules/tokenizers.py", line 4, in &lt;module&gt;
>     jieba.load_userdict('E:\Captionv0\Code\SGF\Data\key_technical_words.txt')
>   File "/home/tyk/anaconda3/envs/aloha/lib/python3.8/site-packages/jieba/__init__.py", line 398, in load_userdict
>     f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Captionv0\\Code\\SGF\\Data\\key_technical_words.txt'

It seems that the essential .txt file is not included in the provided dataset. Is this file crucial, or is its absence negligible for the project?

**Comment by MoramiSu** [comment]
Thank you very much for your attention to our work. The technical word file is a special word list that we manually extract from medical reports for better tokenization. This file also includes special tokens that replace numbers as mentioned in the paper. We have already uploaded the relevant file and you can find it in the dataset link.
